apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: ${CLUSTER_NAME}-md-0
spec:
  clusterName: ${CLUSTER_NAME}
  replicas: ${WORKER_MACHINE_COUNT}
  selector:
    matchLabels:
  template:
    spec:
      clusterName: ${CLUSTER_NAME}
      version: "${KUBERNETES_VERSION}"
      bootstrap:
        configRef:
          name: ${CLUSTER_NAME}-md-0
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: ${CLUSTER_NAME}-md-0
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: LinodeMachineTemplate
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: LinodeMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-md-0
spec:
  template:
    spec:
      image: ${LINODE_OS}
      type: ${LINODE_MACHINE_TYPE}
      region: ${LINODE_REGION}
      authorizedKeys:
        - ${LINODE_SSH_KEY}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: ${CLUSTER_NAME}-md-0
spec:
  template:
    spec:
      files:
        - path: /etc/containerd/config.toml
          contentFrom:
            secret:
              name: common-init-files
              key: containerd-config.toml
        - path: /etc/modules-load.d/k8s.conf
          contentFrom:
            secret:
              name: common-init-files
              key: k8s-modules.conf
        - path: /etc/sysctl.d/k8s.conf
          contentFrom:
            secret:
              name: common-init-files
              key: sysctl-k8s.conf
        - path: /kubeadm-pre-init.sh
          contentFrom:
            secret:
              name: common-init-files
              key: kubeadm-pre-init.sh
          permissions: "0500"
      preKubeadmCommands:
        - /kubeadm-pre-init.sh '{{ ds.meta_data.label }}' "${KUBERNETES_VERSION}"
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
            provider-id: 'linode:///{{ ds.meta_data.region }}/{{ ds.meta_data.id }}'
          name: '{{ ds.meta_data.label }}'
