## Append samples of your project ##
resources:
- infrastructure_v1alpha2_linodecluster.yaml
- infrastructure_v1alpha2_linodemachine.yaml
- infrastructure_v1alpha2_linodevpc.yaml
- infrastructure_v1alpha2_linodeobjectstoragebucket.yaml
- infrastructure_v1alpha2_linodeclustertemplate.yaml
- infrastructure_v1alpha2_linodemachinetemplate.yaml
- infrastructure_v1alpha2_linodefirewall.yaml
- infrastructure_v1alpha2_addressset.yaml
- infrastructure_v1alpha2_firewallrule.yaml
- infrastructure_v1beta1_linodecluster.yaml
- infrastructure_v1beta1_linodemachine.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
