## Append samples of your project ##
resources:
- infrastructure_v1alpha1_linodecluster.yaml
- infrastructure_v1alpha1_linodemachine.yaml
- infrastructure_v1alpha1_linodemachinetemplate.yaml
- infrastructure_v1alpha1_linodeclustertemplate.yaml
- infrastructure_v1alpha1_linodevpc.yaml
- infrastructure_v1alpha1_linodeobjectstoragebucket.yaml
- infrastructure_v1alpha1_linodefirewall.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
