namespace: default
resources:
  - clusterclass.yaml
  - linode-cluster-template.yaml
  - linode-machine-controlplane-template.yaml
  - linode-machine-worker-template.yaml
  - kubeadm-controlplane-template.yaml
  - kubeadm-config-template.yaml
  - ../../common-init-files
